#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Container_Drop)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Container_Pickup)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Container_Relocate)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Container_HarvestCrops)
